### ISSUE TITLE
Icon and text are not aligned

### ISSUE THREAD

**Issue by ky0nch3ng** [invom/Material-T#1]
![](https://i.imgur.com/udnCZzE.png)

footer:
![](https://i.imgur.com/j1lKIP5.png)

**Comment by invom** [comment]
Thanks for your contribution, the problem has been fixed in [cbe03ae6a460132f1a76f842d03d879c93c9b5e1](https://github.com/invom/Material-T/commit/cbe03ae6a460132f1a76f842d03d879c93c9b5e1)
