### ISSUE TITLE
Toc

### ISSUE THREAD

**Issue by glazec** [invom/Material-T#16]
toc文字的颜色会和背景图片冲突

**Comment by glazec** [comment]
![image](https://user-images.githubusercontent.com/22890026/52157443-e6e5e080-2643-11e9-91d8-62d7308399b4.png)
![image](https://user-images.githubusercontent.com/22890026/52157455-f2d1a280-2643-11e9-89ef-b746dccb4e06.png)
抱歉，我之前没有说清楚。随着向下滚动页面，toc会和图片重合。或许可以固定一下toc的位置，不让它和最顶部的图片重合

**Comment by invom** [comment]
这确实是个问题，修复ing

**Comment by glazec** [comment]
如果我想对这个项目做contribute，有什么规范么

**Comment by invom** [comment]
:joy: 只要pr的时候说一下主要改动就好。

**Comment by invom** [comment]
只是通过关闭视差效果来临时修复这个问题，还需要更完美的修复方法
