### ISSUE TITLE
Redesigning

### ISSUE THREAD

**Issue by invom** [invom/Material-T#23]
The project is being redesigned by @zhugaoqi  and I, the new version will be more professional and attractive.

**Comment by iamNCJ** [comment]
Nice Job!
Much Better than Material!

**Comment by HarborZeng** [comment]
Expecting

**Comment by iamNCJ** [comment]
记得之前版本中首页的标题会随页面一起滚动，但是更新后没了，希望可以恢复

**Comment by invom** [comment]
@iamNCJ 你好，是首页 `banner_img` 中的那段字吗

**Comment by iamNCJ** [comment]
@invom 是的

**Comment by elegantYU** [comment]
请问现在主题的about页面出现“Cannot GET /about/” 也是因为在重制吗

**Comment by invom** [comment]
@elegantYU 你好，我猜你需要这个 [传送门](https://invom.github.io/Material-T-docs/pages/about.html)

**Comment by elegantYU** [comment]
@invom 是极是极，多谢

**Comment by huanglongxin** [comment]
怎么添加tag导航呢

**Comment by invom** [comment]
@huanglongxin 你好，归档页目前就是以 tag 来划分文章的，没有单独的 tag 和 category 页。

**Comment by huanglongxin** [comment]
[![QQ截图20190313125000.png](https://i.loli.net/2019/03/13/5c888c131a35e.png)](https://i.loli.net/2019/03/13/5c888c131a35e.png)
请教大佬，这里的title在哪设置

**Comment by invom** [comment]
@huanglongxin 是博客的 subtitle ，内容在 Hexo 的配置文件中设置，主题的配置文件仅能设置是否开启。
