### ISSUE TITLE
代码行数

### ISSUE THREAD

**Issue by grcen** [invom/Material-T#24]
![image](https://user-images.githubusercontent.com/39754645/52902977-4dc5e500-3253-11e9-8eea-b75a5aa5514f.png)

**Comment by grcen** [comment]
请问这个代码行数的问题如何解决？

**Comment by GeZiyue** [comment]
要把hexo自带的highlight关闭

**Comment by grcen** [comment]
怎么添加新的分类？我试了网上的方法发现没效果。

**Comment by invom** [comment]
你好 @grcen ， `Material-T` 是以标签作为文章分类的，直接在文章里添加 `tags` 属性就可以了。
