### ISSUE TITLE
Material-T/layout/index.ejs 报错

### ISSUE THREAD

**Issue by Alfxjx** [invom/Material-T#25]
Line 9
![image](https://user-images.githubusercontent.com/28646799/53163176-7ad61700-3608-11e9-9841-b0df2cdf0559.png)
![image](https://user-images.githubusercontent.com/28646799/53163206-8e817d80-3608-11e9-881b-3de7407ac21f.png)

**Comment by invom** [comment]
你好 @Alfxjx ，我没能复现出报错，尝试一下 `hexo clean` 再`heox g`

**Comment by Alfxjx** [comment]
1，您好，我从vscode换到了webstorm这个error就消失了。

2，之前主要就是index页面的文章缩略图不显示，后来我把`front-matter`里面的index_img的地址从../source/_posts改到了一个新建的../source/post_img，就可以显示了。想问一下缩略图的地址是必须要在source/post_img下面吗

**Comment by invom** [comment]
涉及到的 Hexo 解析逻辑是这样的：

1. 从 `/source/_posts` 中读取文章内容渲染成HTML；
2. 将 `/themes/Material-T/source/` 下的文件全部拷贝到网站根目录；

所以建议所有图片引用使用相对于根目录的 url ，比如我把图片放到 `/themes/Material-T/source/here_is_my_img/` ，引用的时候链接应为 `/here_is_my_img/***.jpg`。

**Comment by Alfxjx** [comment]
明白了，谢谢指导！
