### ISSUE TITLE
关于摘要和文章首页略缩图

### ISSUE THREAD

**Issue by G0doot** [invom/Material-T#3]
文章的摘要可以通过 `<!-- more -->` 开启，但是缩略图一直没有找到方法开启，能不能增加这部分的使用文档。

**Comment by invom** [comment]
Hi @G0doot ,在 文章.md中配置`index_img`属性即可，[示例](https://github.com/invom/invom.github.io/blob/source/source/_posts/hello-world.md) 。

[文档](https://github.com/invom/Material-T/wiki/%E6%96%87%E7%AB%A0-Post)已修正，感谢反馈。

**Comment by G0doot** [comment]
感谢，非常喜欢这个主题。
