### ISSUE TITLE
index_img of post, doesn't become the header image on opening the post,  index_img的帖子，不会成为打开帖子的标题图片

### ISSUE THREAD

**Issue by vaibhavbarmy** [invom/Material-T#5]
index_img is only used in the home page while it should also be used in the header image of the post.
currently header image of post is set to ../img/post-head.jpg
How to make changes so that it takes index_img

index_img仅在主页中使用，同时它也应该在帖子的标题图像中使用
目前帖子的标题图片设置为../img/post-head.jpg
如何进行更改以使其占用index_img

**Comment by invom** [comment]
It was implemented in this [cd62dec](https://github.com/invom/Material-T/commit/cd62decaa1885198e0ff9afc8af58798d06de05e).
Now you can set the property `head_img` in the yourarticle.md to select the top image.

**Comment by invom** [comment]
https://github.com/invom/Material-T/wiki/%E9%A1%B6%E9%83%A8%E5%9B%BE%E5%83%8F-Head-Img
