### ISSUE TITLE
Clicking image of post doesn't open corresponding post. 点击帖子图片不会打开相应的帖子

### ISSUE THREAD

**Issue by vaibhavbarmy** [invom/Material-T#6]
Seeing the website on mobile device, clicking on thumbnail image for a post doesn't open the corresponding post.
在移动设备上查看网站，点击缩略图图片查找帖子不会打开相应的帖子。

Would be great if this small feature can be added.
如果可以添加这个小功能会很棒

Thanks for sharing this beautiful theme for hexo.
感谢分享这个美丽的主题为hexo

**Comment by invom** [comment]
It's done, thanks for your advice
