### ISSUE TITLE
标题过长后移动端显示有问题

### ISSUE THREAD

**Issue by PFISH1998** [invom/Material-T#7]

**Comment by invom** [comment]
你好 @PFISH1998 ，能贴张截图或者预览地址吗

**Comment by PFISH1998** [comment]
直接看我博客这个文章：https://pfish.xyz/2019/01/17/ComputerNetworkNote/
它标题会飘出去

**Comment by PFISH1998** [comment]
用手机打开和把电脑浏览器调整成移动端比例都会看得到

**Comment by invom** [comment]
@PFISH1998 [已修复](https://github.com/invom/Material-T/commit/bd6270aa0e36cfac2a05b091fa81400f47dd76de)，感谢反馈 :+1:

**Comment by PFISH1998** [comment]
👍

**Comment by PFISH1998** [comment]
刚git pull了最近的更新，发现这个问题好像还是存在？😱

**Comment by PFISH1998** [comment]
好像没pull下来，抱歉了

**Comment by invom** [comment]
刚刚对配置文件有比较大的改动，更新前记得备份原配置😂

**Comment by PFISH1998** [comment]
果然翻车了。。。 本地hexo s 后： http://cdn.pfish.xyz/pic/20190126/1xWMFbqv75nm.png?imageslim

**Comment by invom** [comment]
抱歉，按照最新的_config.yml重新填写一遍配置吧，这个报错应该是因为配置文件没更新正确

**Comment by PFISH1998** [comment]
懂了，辛苦啦

**Comment by invom** [comment]
@PFISH1998 昨晚的push出了一些问题，[f302c0f](https://github.com/invom/Material-T/commit/f302c0f8a87d5d93c8ae9fb1386cbc93558c83f2)已解决，重新配置_config.yml文件就可以解决报错，实在是抱歉 :cry:

**Comment by PFISH1998** [comment]
小问题，已经搞定！辛苦
